language: node_js
os:
- linux
- osx
env:
- CXX=g++-4.8
compiler:
- gcc
- clang
node_js:
- '0.10'
- '0.12'
- 4
- 6
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
    - g++-4.8
    - g++-4.8-multilib
    - gcc-multilib
sudo: false
before_install:
- if [[ $TRAVIS_OS_NAME == "linux" ]]; then export CXX=g++-4.8; fi
- if [[ $TRAVIS_OS_NAME == "osx" ]]; then brew install gcc48; fi
- $CXX --version

- PUBLISH_BINARY=false
- echo $TRAVIS_BRANCH
- echo `git describe --tags --always HEAD`

- case ${TRAVIS_NODE_VERSION} in 0.8*|0.10*) npm install -g npm@2 ;; esac
- npm config set progress false
- npm config set spin false
- npm install node-gyp -g
- npm install -g node-gyp
- npm install -g node-pre-gyp
install:
- npm install --build-from-source
